---
- name: set up load-balancers  
  hosts: frontends
  become: yes
  roles:
    - {name: base, tags: base }
    - {name: haproxy, tags: [lb, haproxy]}

- name : setup app servers
  hosts: apps
  become: yes
  roles: 
    - {name: base, tags: base }
    - {name: app, tags: [app, tomcat]}
    - {name: apache, tags: [apache, httpd]}

- name: setup database servers
  hosts: appdbs
  become: yes 
  roles: 
    - {name: base, tags: base }
#    - {name: postgresql, tags: [db, postgresql]}
    - name: ansible-role-postgresql
      tags: db, postgresql
      vars:
        postgresql_databases:
          - name: example_db
        postgresql_users:
          - name: example_user
            password: supersecure
