---
# tasks file for base
- name: enable repos
  template:
    src: repos.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: install httpie
  yum:
    name: httpie
    state: latest
